package com.kmp.aeroparker.subscription.payments.affiliate.config;

public enum AffiliateConfigKeys
{
	ALLOW_CANCEL_WITHOUT_REFUND,
	ALLOW_CANCEL_WITHOUT_REFUND_DATE,
	ALLOW_ONLY_FULL_REFUND,
	ALLOW_SIGNIN_PARKING_CONTINUE_AS_GUEST,
	BARRIER_CODE,
	BRAINTREE_FIELDS_DISPLAY_SINGLE_LINE,
	CONF_SHOW_ACCOUNT_CREATION_FORM,
	CONF_SHOW_COMPANY_DETAILS,
	CONF_SHOW_LONG_LAT_COORDINATES,
	DEDUCT_BOOKING_FEE_FROM_DISPLAY_SAVINGS,
	DEFAULT_PRODUCT_SORTING,
	DEFAULT_VIEW,
	DISALLOW_CHANGE_PERSONAL_DETAILS,
	DISPLAY_FULL_TAX_BREAKDOWN_BOOKING_SUMMARY,
	DISPLAY_STYLE,
	DISPLAY_TCS_SECTION,
	DISPLAY_TCS_CHECKBOX,
	EMAIL_VALIDATION_LICENSE_KEY,
	ENABLE_APPLE_PASSKIT,
	ENABLE_EMAIL_CONFIRMATIONS,
	ENABLE_GRID,
	ENABLE_LIST,
	ENABLE_OPT_INS,
	ENABLE_PAYPAL_PAYMENTS,
	ENABLE_SIGNIN_ON_STEP4,
	ENABLE_SIGNIN_PARKING_STEP,
	HIDE_ALL_TIMES_IN_FRONT_END,
	IS_EMAIL_VALIDATION_ENABLED,
	IS_INTERPARKING,
	MULTIPURCHASE_AGES_DISPLAY_ADULT,
	MULTIPURCHASE_AGES_DISPLAY_CHILD,
	MULTIPURCHASE_AGES_DISPLAY_INFANT,
	MULTIPURCHASE_AGES_DISPLAY_MAX_NUM_ADULTS,
	MULTIPURCHASE_AGES_DISPLAY_MAX_NUM_CHILDREN,
	MULTIPURCHASE_AGES_DISPLAY_MAX_NUM_INFANTS,		
	MULTIPURCHASE_BOOKING_TIMES_MIN_MINUTE,
	MULTIPURCHASE_BOOKING_TIMES_MIN_HOUR,
	MULTIPURCHASE_BOOKING_TIMES_MAX_MINUTE,
	MULTIPURCHASE_BOOKING_TIMES_MAX_HOUR,
	MULTIPURCHASE_BOOKING_TIMES_MINUTE_STEP,
	MULTIPURCHASE_CSS_SHEET_URL,
	MULTIPURCHASE_STEP1_TITLE,
	MULTIPURCHASE_STEP1_SUBTITLE,
	MULTIPURCHASE_STEP1_MIDSECTION_TEXT,
	MULTIPURCHASE_STEP2_DISPLAY_PRODUCT_IMAGES,
	MULTIPURCHASE_STEP2_DISPLAY_PRODUCT_HEADLINES,
	PAGE_TITLES_AFFILIATE_NAME,
	MULTIPURCHASE_STEP3_DISPLAY_PRODUCT_IMAGES,
	MULTIPURCHASE_STEP3_DISPLAY_PRODUCT_HEADLINES,
	PARKING_STEP3_DISPLAY_PRODUCT_IMAGES,
	PARKING_STEP3_DISPLAY_PRODUCT_HEADLINES,
	PURCHASE_STEP1_LISTITEMS,
	PURCHASE_STEP3_DISPLAY_PRODUCT_IMAGES,
	PURCHASE_STEP3_DISPLAY_PRODUCT_HEADLINES,
	REVIEWS_STORE,
	ROUND_TO_WHOLE_CURRENCY_UNIT,
	SHOW_BOOKING_SUMMARY_TOP_BUTTON,
	SEND_CONF_AFTER_BARRIER_SEND,
	SHOW_PRINT_BUTTON_ON_CONF_PAGE,
	SHOWVEHICLELOOKUP,
	STEP1_DISPLAY_STYLE,
	STEP1_SHOW_PROMOCODE_FIELD,
	STEP1_SHOW_AIRLINE_FIELD,
	STEP1_SHOW_FLIGHT_LOOKUP,
	STEP1_DISPLAY_TERMINAL_DROPDOWN,
	STEP2_DISPLAY_STYLE,
	STEP2_GRID_NUMBER_OF_ROWS,
	STEP2_HIDE_PRODUCT_HEADERS,
	STEP4_SHOW_PROMOCODE_FIELD,
	STEP4_SHOW_AIRLINE_FIELD,
	ENABLE_ACTIVATE_ACCOUNT_EMAIL,
	ENABLE_FORGOT_PASSWORD_EMAIL,
	SHOW_CREATE_ACCOUNT_HEADER,
	ENABLE_ACCOUNT_CREATION_ON_DETAILS_STEP,
	SHOW_POSTCODE_LOOKUP,
	ENABLE_ACCOUNT_CREATED_EMAIL,
	ENABLE_QUICK_PLATE_CHANGE,
	ENABLE_POST_PURCHASE,
	STEP1_USE_FLIGHT_LOOKUP_FOR_TIMES,
	SUBSCRIPTION_CSS_SHEET_URL,
	EXTERNAL_API_ENDPOINT,
	EXTERNAL_API_USERNAME,
	EXTERNAL_API_PASSWORD;
	
	
	public static AffiliateConfigKeys customValueOf(String strEnum)
	{
		for (AffiliateConfigKeys config : values())
		{
			if (config.toString()
					.equalsIgnoreCase(strEnum))
			{
				return config;
			}
		}
		return null;
	}
}