<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.kmp.aeroparker</groupId>
	<artifactId>aeroparker-subscription</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>
	<modules>
		<module>aeroparker-subscription-booking</module>
		<module>aeroparker-subscription-db-config</module>
		<module>aeroparker-subscription-booking-generated</module>
		<module>aeroparker-subscription-utils</module>
		<module>aeroparker-subscription-payments</module>
		<module>aeroparker-subscription-payments-generated</module>
	</modules>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<spring-boot-version>2.7.4</spring-boot-version>
		<mysql-connector-version>8.0.30</mysql-connector-version>
		<maven-clean-plugin-version>3.0.0</maven-clean-plugin-version>
		<aeroparker-version>1.0.0</aeroparker-version>
		<github-benas-version>3.7.0</github-benas-version>
		<braintree-java-version>3.46.0</braintree-java-version>
		<org.apache.commons-version>1.9</org.apache.commons-version>
		<net.trajano.commons-version>2.1.0</net.trajano.commons-version>
		<dockerfile-maven-plugin-version>1.4.13</dockerfile-maven-plugin-version>
		<jooq-version>3.14.16</jooq-version>
		<aws-sqs-version>1.12.772</aws-sqs-version>
		<bean-matchers-version>0.14</bean-matchers-version>
	</properties>

	<distributionManagement>
		<repository>
			<id>central</id>
			<name>releases</name>
			<url>${url.libs-release}</url>
		</repository>
		<snapshotRepository>
			<id>snapshots</id>
			<name>snapshots</name>
			<url>${url.libs-snapshot}</url>
		</snapshotRepository>
	</distributionManagement>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot-version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>2.8.2</version>
					<configuration>
						<deployAtEnd>true</deployAtEnd>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.0.0-M3</version>
				</plugin>
				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<version>0.8.11</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<extensions>
			<extension>
				<groupId>com.gkatzioura.maven.cloud</groupId>
				<artifactId>s3-storage-wagon</artifactId>
				<version>1.2</version>
			</extension>
		</extensions>
	</build>
</project>