<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.kmp.aeroparker</groupId>
		<artifactId>aeroparker-subscription</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>aeroparker-subscription-booking-generated</artifactId>
	<dependencies>
		<dependency>
			<groupId>com.kmp.aeroparker</groupId>
			<artifactId>aeroparker-subscription-db-config</artifactId>
			<version>${aeroparker-version}</version>
		</dependency>
	</dependencies>
	<build>
		<finalName>aeroparker-subscription-booking-generated</finalName>
		<plugins>
			<plugin>
				<groupId>org.jooq</groupId>
				<artifactId>jooq-codegen-maven</artifactId>
				<version>${jooq-version}</version>
				<executions>
					<execution>
						<id>tenants</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<jdbc>
								<url>${jdbc.url}</url>
								<user>${jdbc.user}</user>
								<password>${jdbc.password}</password>
							</jdbc>
							<generator>
								<name>org.jooq.codegen.JavaGenerator</name>
								<database>
									<name>org.jooq.meta.mysql.MySQLDatabase</name>
									<includes>.*</includes>
									<inputSchema>tenants</inputSchema>
									<outputSchemaToDefault>true</outputSchemaToDefault>
								</database>
								<strategy>
									<!-- Strategies cannot be in the same project as the generated code, 
										must be in another project that is added as a dependency -->
									<name>com.kmp.aeroparker.db.jooq.strategy.SubscriptionPojoDaoStrategy</name>
								</strategy>
								<target>
									<packageName>com.kmp.aeroparker.subscription.booking.tenants</packageName>
									<directory>src/main/generated</directory>
								</target>
								<generate>
									<pojos>true</pojos>
									<records>false</records>
								</generate>
							</generator>
						</configuration>
					</execution>
					<execution>
						<id>subscription</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<jdbc>
								<url>${jdbc.url}</url>
								<user>${jdbc.user}</user>
								<password>${jdbc.password}</password>
							</jdbc>
							<generator>
								<name>org.jooq.codegen.JavaGenerator</name>
								<database>
									<name>org.jooq.meta.mysql.MySQLDatabase</name>
									<includes>
										ab_affiliates_display|ab_emails|ab_contacts_activation_codes|ab_affiliates_metadata|ab_affiliates_footer_pages|affiliate_subscription|affiliate_custom_email|
										affiliate_subscription_media|subscription_product|subscription_product_terms|subscription_product_appearance|affiliate_subscription_product|
										payment_step_fields_subscriptions|locations|currencies|subscription_guid|subscription_booking|subscription_guid_booking|ab_sequence|ab_carparks|subscription_purchase_data|subscription_booking_customer_details|
										subscription_booking_season_ticket|subscription_booking_item|crm_subscription_email|crm_subscription_email_appearance|email_queue|ab_contacts|site_subscription_recurring_payment|
										ab_affiliates_languages|ab_lang_sections_servlets|ab_affiliates_content|subscription_booking_recurring_ticket|affiliate_subscription_settings|affiliates_crm_opt_in|subscription_booking_vehicle_details|
										contact_hashed_password|ab_affiliates_languages|ab_lang_sections_servlets|ab_affiliates_content|subscription_booking_recurring_ticket|affiliate_subscription_settings|affiliates_crm_opt_in|subscription_booking_vehicle_details|
										subscription_booking_receipt_details|subscription_booking_payment|subscription_all_booking_data|subscription_booking_reservation_data|subscription_booking_language|feature_flag|company|payment_invoice|
										site_ancillary_barcode_configuration|site_ancillary_barcode_configuration_subscription_product|subscription_discounted_renewal|subscription_booking_details|subscription_booking_encrypted|subscription_booking_car_park|
										subscription_custom_value|subscription_membership_sequence|subscription_contact_membership|subscription_product_car_park|subscription_reference_sequence|vehiclelookup_affiliate_logins|quotas_subscription|quotas_subscription_product|
										subscription_booking_ticket|ab_affiliates|subscription_invoice_url|subscription_booking_membership|payment_step_fields_subscription_products|company_subscription|affiliate_analytics_new|subscription_tracking|subscription_promo_booking|subscription_session_promotion
										|promotions_promo_codes
									</includes>
									<inputSchema>kmp_advancebooker</inputSchema>
									<outputSchemaToDefault>true</outputSchemaToDefault>
								</database>
								<strategy>
									<!-- Strategies cannot be in the same project as the generated code, 
										must be in another project that is added as a dependency -->
									<name>com.kmp.aeroparker.db.jooq.strategy.SubscriptionPojoDaoStrategy</name>
								</strategy>
								<generate>
									<deprecated>false</deprecated>
									<pojos>true</pojos>
									<daos>true</daos>
									<javaTimeTypes>false</javaTimeTypes>
								</generate>
								<target>
									<packageName>com.kmp.aeroparker.subscription.booking.kmp</packageName>
									<directory>src/main/generated</directory>
								</target>
							</generator>
						</configuration>
					</execution>
					<execution>
						<id>api</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<jdbc>
								<url>${jdbc.url}</url>
								<user>${jdbc.user}</user>
								<password>${jdbc.password}</password>
							</jdbc>
							<generator>
								<name>org.jooq.codegen.JavaGenerator</name>
								<database>
									<name>org.jooq.meta.mysql.MySQLDatabase</name>
									<includes>api_user|api_user_settings</includes>
									<inputSchema>api</inputSchema>
									<outputSchemaToDefault>true</outputSchemaToDefault>
								</database>
								<strategy>
									<!-- Strategies cannot be in the same project as the generated code, 
										must be in another project that is added as a dependency -->
									<name>com.kmp.aeroparker.db.jooq.strategy.SubscriptionPojoDaoStrategy</name>
								</strategy>
								<target>
									<packageName>com.kmp.aeroparker.subscription.booking.api</packageName>
									<directory>src/main/generated</directory>
								</target>
								<generate>
									<pojos>true</pojos>
									<records>false</records>
								</generate>
							</generator>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>mysql</groupId>
						<artifactId>mysql-connector-java</artifactId>
						<version>${mysql-connector-version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/main/generated</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>${maven-clean-plugin-version}</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>src/main/generated</directory>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.jooq</groupId>
										<artifactId>jooq-codegen-maven</artifactId>
										<goals>
											<goal>generate</goal>
										</goals>
										<versionRange>[${jooq-version},)</versionRange>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>