package com.kmp.aeroparker.application.model.enums;

public enum ProcessorType
{
	CONTACT, GUID_BOOKING, CUSTOMER_DETAILS, ITEM_BOOKING, VEHICLE_DETAILS, PASSWORD_CHOICE, RECEIPT_DETAILS,
	BOOKING_PAYMENT, PAYMENT_HISTORY, LANGUAGE, CAR_PARK, SUBSCRIPTION_CONTACT_MEMBERSHIP, 
	SUBSCRIPTION_BOOKING_MEMBERSHIP;
}