CREATE TABLE `currencies` (
  `id` int NOT NULL,
  `code` varchar(3) NOT NULL,
  `symbol` varchar(10) NOT NULL,
  `htmlSymbol` varchar(20) NOT NULL,
  `isoCode` varchar(3) DEFAULT NULL,
  `currencyNumber` varchar(3) DEFAULT NULL,
  `conversionRate` decimal(19,4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_UNIQUE` (`code`)
);

INSERT INTO currencies (id, code, symbol, htmlSymbol, isoCode, currencyNumber, conversionRate) VALUES(16, 'EUR', '€', '&euro;', 'EUR', '978', 1.1617);
CREATE TABLE `languages` (
  `id` int NOT NULL,
  `languageName` varchar(100) NOT NULL,
  `languageCode` varchar(45) NOT NULL,
  `displayCode` varchar(45) NOT NULL,
  `displayName` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO languages (id, languageName, languageCode, displayCode, displayName) VALUES(1, 'English (United Kingdom)', 'en-gb', 'en-gb', 'en');

CREATE TABLE `locations` (
  `id` int NOT NULL,
  `name` varchar(50) NOT NULL,
  `decimalSymbol` varchar(25) NOT NULL,
  `numDigitsAfterDecimal` int NOT NULL,
  `digitGroupSymbol` varchar(25) NOT NULL,
  `digitGrouping` varchar(25) NOT NULL,
  `negNumFormat` varchar(25) NOT NULL,
  `displayLeadingZero` int NOT NULL,
  `currencySymbol` varchar(25) NOT NULL DEFAULT '£',
  `currencyPositiveFormat` varchar(25) NOT NULL,
  `currencyNegativeFormat` varchar(25) NOT NULL,
  `currencyDecimalPlaces` int NOT NULL,
  `currencyGroupingSymbol` varchar(25) NOT NULL,
  `currencyDecimalSymbol` varchar(25) NOT NULL,
  `currencyHidePennies` int NOT NULL,
  `dateFormat` varchar(25) NOT NULL,
  `longDateFormat` varchar(25) NOT NULL,
  `longDateTimeFormat` varchar(45) NOT NULL DEFAULT '',
  `dateFormatSQL` varchar(15) NOT NULL DEFAULT '%d/%m/%Y',
  `dateFormatForReports` varchar(25) NOT NULL DEFAULT 'yyyy-MM-dd',
  `timeShort` varchar(25) NOT NULL,
  `timeLong` varchar(25) NOT NULL,
  `time24hr` int NOT NULL,
  `currency` int NOT NULL DEFAULT '1',
  `isoCode` varchar(2) DEFAULT NULL,
  `calendarStartDay` tinyint(1) NOT NULL DEFAULT '0',
  `countryCallingCode` varchar(5) DEFAULT NULL,
  `sqlLocationCode` varchar(5) DEFAULT 'en_GB',
  `drinkingAge` int DEFAULT NULL,
  `defaultLanguageId` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_locations_name` (`name`),
  KEY `fk_locations_currency_idx` (`currency`),
  KEY `fk_locations_languages_defaultLanguageId_idx` (`defaultLanguageId`),
  CONSTRAINT `fk_locations_currency` FOREIGN KEY (`currency`) REFERENCES `currencies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_locations_languages_defaultLanguageId` FOREIGN KEY (`defaultLanguageId`) REFERENCES `languages` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO locations (id, name, decimalSymbol, numDigitsAfterDecimal, digitGroupSymbol, digitGrouping, negNumFormat, displayLeadingZero, currencySymbol, currencyPositiveFormat, currencyNegativeFormat, currencyDecimalPlaces, currencyGroupingSymbol, currencyDecimalSymbol, currencyHidePennies, dateFormat, longDateFormat, longDateTimeFormat, dateFormatSQL, dateFormatForReports, timeShort, timeLong, time24hr, currency, isoCode, calendarStartDay, countryCallingCode, sqlLocationCode, drinkingAge, defaultLanguageId) VALUES(33, 'Ireland', '.', 2, ',', '123,456,789', '-1.1', 1, '£', '&pound;1.1', '-&pound;1.1', 2, ',', '.', 0, 'dd/MM/yyyy', 'EEE, dd MMMM yy', '', '%d/%m/%Y', 'yyyy-MM-dd', 'hh:mm tt', 'hh:mm:ss tt', 1, 16, NULL, 0, '+44', 'en_IE', NULL, NULL);

CREATE TABLE `ab_sites` (
  `id` int NOT NULL,
  `title` varchar(255) NOT NULL,
  `siteType` varchar(10) NOT NULL DEFAULT 'AIRPORT',
  `numberOfTerminals` int NOT NULL DEFAULT '1',
  `isEnabled` smallint NOT NULL DEFAULT '0',
  `url` varchar(255) DEFAULT NULL,
  `paxPerWeek` int NOT NULL DEFAULT '0',
  `locationId` int NOT NULL,
  `timezone` varchar(63) NOT NULL DEFAULT 'Etc/GMT',
  `secondsFromGMT` int NOT NULL DEFAULT '0',
  `defaultStateCode` varchar(45) DEFAULT '',
  `defaultLanguageId` int DEFAULT NULL,
  `isUserAccountsEnabled` int NOT NULL,
  `passwordChangeDays` smallint NOT NULL DEFAULT '30',
  `isDesignaPinEnabled` int NOT NULL DEFAULT '0',
  `alertEmails` varchar(60) DEFAULT NULL,
  `barrierSystemServerId` int DEFAULT '0',
  `facilityName` varchar(255) DEFAULT NULL,
  `useDummyData` int NOT NULL DEFAULT '0',
  `vatRate` decimal(13,2) NOT NULL DEFAULT '20.00',
  `thirdPartyAvailabilityCheckEnabled` int NOT NULL DEFAULT '0',
  `additionalParkingAvailabilityFields` bit(1) DEFAULT b'0',
  `lengthOfStayType` smallint NOT NULL DEFAULT '1',
  `allowConsolidatorEmailResend` int NOT NULL DEFAULT '0',
  `defaultAffiliateId` int DEFAULT NULL,
  `productCodeMandatoryCheckEnabled` bit(1) NOT NULL DEFAULT b'0',
  `locationName` varchar(60) NOT NULL DEFAULT 'Terminal',
  `enableSendingFeedback` bit(1) NOT NULL DEFAULT b'0',
  `apiReserveBooking` bit(1) NOT NULL DEFAULT b'0',
  `apiTakePayment` bit(1) NOT NULL DEFAULT b'0',
  `apiPreventOverlappingBookings` bit(1) NOT NULL DEFAULT b'0',
  `airportCode` varchar(3) NOT NULL DEFAULT '',
  `defaultLocationName` varchar(255) DEFAULT '',
  `includeSoldOutInApi` bit(1) NOT NULL DEFAULT b'0',
  `preventDuplicateBookings` bit(1) NOT NULL DEFAULT b'0',
  `passwordReuseLimitAdmin` smallint NOT NULL DEFAULT '4',
  `passwordChangeDaysCallCentre` smallint NOT NULL DEFAULT '30',
  `passwordReuseLimitCallCentre` smallint NOT NULL DEFAULT '4',
  `enableCountryCodesFlagInput` bit(1) DEFAULT b'0',
  `passwordChangeDaysAgency` smallint NOT NULL DEFAULT '30',
  `passwordReuseLimitAgency` smallint NOT NULL DEFAULT '4',
  `bucketCalculationMethod` smallint NOT NULL DEFAULT '1',
  `apiEnableRequiredFields` bit(1) NOT NULL DEFAULT b'0',
  `includeProductCategoriesOnParkingAvailability` bit(1) NOT NULL DEFAULT b'0',
  `includePaymentMethodsInParkingAvailability` bit(1) NOT NULL DEFAULT b'0',
  `apiEnableIncludeGrace` bit(1) NOT NULL DEFAULT b'0',
  `apiSkipAvailabilityWithinWindow` bit(1) NOT NULL DEFAULT b'0',
  `validatePromotionOnAmendment` bit(1) NOT NULL DEFAULT b'0',
  `apiReserveTicketsWhenKeyIsValid` bit(1) NOT NULL DEFAULT b'0',
  `ccDefaultSearchDate` smallint NOT NULL DEFAULT '0',
  `showAllWhiteLabelAffiliateBookings` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `fk_sites_locationId_idx` (`locationId`),
  KEY `fk_sites_defaultLanguageId_idx` (`defaultLanguageId`),
  CONSTRAINT `fk_sites_defaultLanguageId` FOREIGN KEY (`defaultLanguageId`) REFERENCES `languages` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_sites_locationId` FOREIGN KEY (`locationId`) REFERENCES `locations` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

INSERT INTO ab_sites (id, title, siteType, numberOfTerminals, isEnabled, url, paxPerWeek, locationId, timezone, secondsFromGMT, defaultStateCode, defaultLanguageId, isUserAccountsEnabled, passwordChangeDays, isDesignaPinEnabled, alertEmails, barrierSystemServerId, facilityName, useDummyData, vatRate, thirdPartyAvailabilityCheckEnabled, additionalParkingAvailabilityFields, lengthOfStayType, allowConsolidatorEmailResend, defaultAffiliateId, productCodeMandatoryCheckEnabled, locationName, enableSendingFeedback, apiReserveBooking, apiTakePayment, apiPreventOverlappingBookings, airportCode, defaultLocationName, includeSoldOutInApi, preventDuplicateBookings, passwordReuseLimitAdmin, passwordChangeDaysCallCentre, passwordReuseLimitCallCentre, enableCountryCodesFlagInput, passwordChangeDaysAgency, passwordReuseLimitAgency, bucketCalculationMethod, apiEnableRequiredFields, includeProductCategoriesOnParkingAvailability, includePaymentMethodsInParkingAvailability, apiEnableIncludeGrace, apiSkipAvailabilityWithinWindow, validatePromotionOnAmendment, apiReserveTicketsWhenKeyIsValid, ccDefaultSearchDate, showAllWhiteLabelAffiliateBookings) VALUES(27, 'Shannon Airport', 'AIRPORT', 1, 1, 'http://www.shannonairport.ie/', 0, 33, 'Etc/GMT', 0, '', 1, 1, 0, 0, '', 0, '', 0, 20.00, 0, 1, 1, 0, 71, 0, 'Terminal', 0, 0, 0, 0, 'SNN', '', 0, 0, 4, 30, 4, 0, 30, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);

CREATE TABLE `ab_affiliates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(30) NOT NULL,
  `name` varchar(255) NOT NULL,
  `companyName` varchar(255) NOT NULL,
  `type` int NOT NULL DEFAULT '0',
  `defaultPromoCode` varchar(255) NOT NULL,
  `siteid` int NOT NULL,
  `isEnabled` int NOT NULL DEFAULT '0',
  `bookingReferenceFormat` varchar(30) NOT NULL DEFAULT '{S}{R}{P}{I}',
  `bookingReferencePrefix` varchar(5) NOT NULL DEFAULT 'W',
  `bookingSequenceName` varchar(80) NOT NULL DEFAULT 'bookings',
  `paymentPropertiesNode` varchar(50) DEFAULT NULL,
  `bookingFee` decimal(13,2) NOT NULL DEFAULT '0.00',
  `bookingFeeType` smallint NOT NULL DEFAULT '1',
  `refundBookingFeeOnCancellation` int NOT NULL DEFAULT '0',
  `debitCardFee` decimal(13,2) NOT NULL DEFAULT '0.00',
  `debitCardFeeType` smallint NOT NULL DEFAULT '0',
  `creditCardFee` decimal(13,2) NOT NULL DEFAULT '0.00',
  `creditCardFeeType` smallint NOT NULL DEFAULT '0',
  `paypalFee` decimal(13,2) NOT NULL DEFAULT '0.00',
  `paypalUsePercent` int NOT NULL DEFAULT '0',
  `refundCardFeeOnCancellation` int NOT NULL DEFAULT '0',
  `cancellationCharge` decimal(13,2) NOT NULL DEFAULT '0.00',
  `cancellationChargeType` smallint NOT NULL DEFAULT '1',
  `amendCancel_minHoursBeforeDateOfArrival` int NOT NULL DEFAULT '0',
  `amendCancel_ignoreTimeOfDay` smallint NOT NULL DEFAULT '0',
  `bookingDateType` smallint NOT NULL DEFAULT '1',
  `vatRate` decimal(13,2) NOT NULL,
  `stateTaxRate` decimal(13,2) NOT NULL DEFAULT '0.00',
  `cityTax` decimal(13,2) DEFAULT '0.00',
  `vatNo` varchar(50) NOT NULL,
  `vatAddress` varchar(255) NOT NULL,
  `vatCompany` varchar(255) NOT NULL,
  `smsAssistancePrice` decimal(13,2) NOT NULL DEFAULT '-1.00',
  `crmType` int NOT NULL DEFAULT '0',
  `enable3DSecure` smallint NOT NULL DEFAULT '0',
  `secure3DPurchaseDesc` varchar(80) DEFAULT NULL,
  `secure3DWebsiteUrl` varchar(255) DEFAULT NULL,
  `callCentreNumber` varchar(50) NOT NULL,
  `isUserAccountsEnabled` int NOT NULL DEFAULT '0',
  `isSaveForLaterEnabled` int NOT NULL DEFAULT '0',
  `isSaveForLaterReminderEnabled` int NOT NULL DEFAULT '0',
  `isSocialLoginEnabled` int NOT NULL DEFAULT '0',
  `isDataCashEnabled` int NOT NULL DEFAULT '0',
  `isPaypalEnabled` int NOT NULL DEFAULT '0',
  `isNetaxeptEnabled` int NOT NULL DEFAULT '0',
  `isMainAffiliate` int NOT NULL DEFAULT '0',
  `cardPaymentsEnabled` int NOT NULL DEFAULT '0',
  `payPalEnabled` int NOT NULL DEFAULT '0',
  `isArchived` tinyint(1) NOT NULL DEFAULT '0',
  `isReferAFriendEnabled` int NOT NULL DEFAULT '0',
  `isStripePaymentEnabled` int DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_UNIQUE` (`code`),
  KEY `siteid` (`siteid`),
  KEY `fk_affils_bookingSequenceName_idx` (`bookingSequenceName`),
  KEY `idx_affils_code` (`code`),
  CONSTRAINT `fk_affils_siteId` FOREIGN KEY (`siteid`) REFERENCES `ab_sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO ab_affiliates (id, code, name, companyName, `type`, defaultPromoCode, siteid, isEnabled, bookingReferenceFormat, bookingReferencePrefix, bookingSequenceName, paymentPropertiesNode, bookingFee, bookingFeeType, refundBookingFeeOnCancellation, debitCardFee, debitCardFeeType, creditCardFee, creditCardFeeType, paypalFee, paypalUsePercent, refundCardFeeOnCancellation, cancellationCharge, cancellationChargeType, amendCancel_minHoursBeforeDateOfArrival, amendCancel_ignoreTimeOfDay, bookingDateType, vatRate, stateTaxRate, cityTax, vatNo, vatAddress, vatCompany, smsAssistancePrice, crmType, enable3DSecure, secure3DPurchaseDesc, secure3DWebsiteUrl, callCentreNumber, isUserAccountsEnabled, isSaveForLaterEnabled, isSaveForLaterReminderEnabled, isSocialLoginEnabled, isDataCashEnabled, isPaypalEnabled, isNetaxeptEnabled, isMainAffiliate, cardPaymentsEnabled, payPalEnabled, isArchived, isReferAFriendEnabled, isStripePaymentEnabled) VALUES(72, 'SNN', 'Shannon Airport', 'Shannon Airport', 1, '', 27, 1, '{S}{R}{P}{I}', 'SN', 'bookings', NULL, 0.00, 2, 0, 0.00, 1, 0.00, 1, 0.00, 0, 0, 0.00, 1, 0, 0, 1, 23.00, 0.00, 0.00, 'IE6411054R', 'Shannon Airport, Co. Clare, Ireland', 'Shannon Airport Authority DAC', -1.00, 0, 0, NULL, NULL, '', 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0);

CREATE TABLE `affiliates_crm_opt_in` (
  `id` int NOT NULL AUTO_INCREMENT,
  `affiliateId` int NOT NULL,
  `type` int NOT NULL DEFAULT '0',
  `message` mediumtext NOT NULL,
  `defaultChecked` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `fk_affOptIn_affId_idx` (`affiliateId`),
  CONSTRAINT `fk_affOptIn_affId` FOREIGN KEY (`affiliateId`) REFERENCES `ab_affiliates` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `affiliates_crm_opt_in`(`id`,`affiliateId`,`type`,`message`,`defaultChecked`) VALUES ('280', '72', '1', 'Opt-in for emails', b'0');
INSERT INTO `affiliates_crm_opt_in`(`id`,`affiliateId`,`type`,`message`,`defaultChecked`) VALUES ('281', '72', '2', 'Opt-in for emails', b'0');


CREATE TABLE `ab_affiliates_footer_pages` (
  `id` int NOT NULL AUTO_INCREMENT,
  `affiliateId` int NOT NULL,
  `languageId` int NOT NULL,
  `linkTitle` varchar(255) NOT NULL,
  `enabled` tinyint NOT NULL DEFAULT '0',
  `content` mediumtext,
  `isLink` tinyint(1) DEFAULT '0',
  `url` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `uq_affiliates_footer_pages_affiliateId_languageId_linkTitle` (`affiliateId`,`languageId`,`linkTitle`),
  KEY `ab_affiliates_footer_pages_affId_idx` (`affiliateId`),
  KEY `ab_affiliates_footer_pages_langId_idx` (`languageId`),
  KEY `ab_affiliates_footer_pages_afflang_idx` (`affiliateId`,`languageId`),
  CONSTRAINT `ab_affiliates_footer_pages_affId` FOREIGN KEY (`affiliateId`) REFERENCES `ab_affiliates` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ab_affiliates_footer_pages_langId` FOREIGN KEY (`languageId`) REFERENCES `languages` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO ab_affiliates_footer_pages (id, affiliateId, languageId, linkTitle, enabled, content, isLink, url) VALUES(1, 72, 1, 'Italy Page', 1, '&lt;p&gt;Test Page Content 2&lt;/p&gt;', 0, NULL);