<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.kmp.aeroparker</groupId>
		<artifactId>aeroparker-subscription</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>aeroparker-subscription-payments-generated</artifactId>
	<dependencies>
		<dependency>
			<groupId>com.kmp.aeroparker</groupId>
			<artifactId>aeroparker-subscription-db-config</artifactId>
			<version>${aeroparker-version}</version>
		</dependency>
	</dependencies>
	<build>
		<finalName>aeroparker-subscription-payments-generated</finalName>
		<plugins>
			<plugin>
				<groupId>org.jooq</groupId>
				<artifactId>jooq-codegen-maven</artifactId>
				<version>${jooq-version}</version>
				<executions>
					<execution>
						<id>payments</id>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<jdbc>
						<url>${jdbc.url}</url>
						<user>${jdbc.user}</user>
						<password>${jdbc.password}</password>
					</jdbc>
					<generator>
						<name>org.jooq.codegen.JavaGenerator</name>
						<database>
							<name>org.jooq.meta.mysql.MySQLDatabase</name>
							<includes>
								ab_sites|payment_gateway_types|selected_payment_gateway|payments|payments_custom_fields|payments_custom_values|
								refunds|payments_processed_token|ab_affiliates|languages|payments_wirecard_response|
								locations|ab_affiliate_config|ab_affiliate_config_values|subscription_scheduled_recurring_payment|subscription_all_booking_data|
								subscription_recurring_payment_sent|klix_session|payment_invoice|partial_payments|partial_payment_amount|partial_payment_version
								|payment_transaction
							</includes>
							<inputSchema>kmp_advancebooker</inputSchema>
							<outputSchemaToDefault>true</outputSchemaToDefault>
							<customTypes>
								<customType>
									<name>VarcharToBigDecimal</name>
									<type>java.math.BigDecimal</type>
									<converter>com.kmp.aeroparker.db.jooq.converters.VarcharToBigDecimalConverter</converter>
								</customType>
							</customTypes>
							<forcedTypes>
								<forcedType>
									<name>VarcharToBigDecimal</name>
									<expression>
										.*partial_payments.amount
									</expression>
									<types>varchar</types>
								</forcedType>
							</forcedTypes>
						</database>
						<strategy>
							<!-- Strategies cannot be in the same project as the generated code, 
								must be in another project that is added as a dependency -->
							<name>com.kmp.aeroparker.db.jooq.strategy.SubscriptionPojoDaoStrategy</name>
						</strategy>
						<generate>
							<deprecated>false</deprecated>
							<pojos>true</pojos>
							<daos>true</daos>
							<javaTimeTypes>false</javaTimeTypes>
						</generate>
						<target>
							<packageName>com.kmp.aeroparker.subscription.payments</packageName>
							<directory>src/main/generated</directory>
						</target>
					</generator>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>mysql</groupId>
						<artifactId>mysql-connector-java</artifactId>
						<version>${mysql-connector-version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/main/generated</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>${maven-clean-plugin-version}</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>src/main/generated</directory>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.jooq</groupId>
										<artifactId>jooq-codegen-maven</artifactId>
										<goals>
											<goal>generate</goal>
										</goals>
										<versionRange>[${jooq-version},)</versionRange>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>